import type { Lesson } from "./types";

/** Risk Management (14 lessons) — position sizing, stop-loss placement, and
 *  risk/reward ratios are exactly what Build the Order grades, so this skill
 *  leans on it heavily, with a handful of Signal Spot lessons for pure-concept
 *  checks that don't reduce to "place 3 sliders" (the 1-2% rule, risk/reward
 *  ratio math, revenge-holding a losing trade, all-in sizing). */
export const LESSONS: Lesson[] = [
  {
    id: "risk-1",
    skillId: "risk",
    title: "Size a long entry",
    type: "build-order",
    scenario:
      "BTC just bounced off a support level that's held three times. You want to go long. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 70, high: 71, low: 64, close: 68 },
      { open: 68, high: 72, low: 66, close: 71 },
      { open: 71, high: 73, low: 64, close: 69 },
      { open: 69, high: 74, low: 67, close: 73 },
      { open: 73, high: 75, low: 64, close: 70 },
      { open: 70, high: 76, low: 69, close: 75 },
    ],
    currentPrice: 75,
    entryDefault: 75,
    stopLossDefault: 70,
    takeProfitDefault: 82,
    entryRange: { min: 73, max: 77 },
    stopLossRange: { min: 62, max: 67 },
    takeProfitRange: { min: 84, max: 96 },
    sliderMin: 55,
    sliderMax: 100,
    sliderStep: 0.5,
    explain:
      "Entry close to the current price (73-77) avoids chasing. The stop belongs just under support (62-67) — tight enough to actually limit the loss, but far enough that normal noise around 64 doesn't stop you out. A take-profit of 84-96 keeps your reward at least 2x the risk you're taking (roughly $8-10 of risk vs. $9-21 of reward) — the minimum ratio worth risking real capital for.",
  },
  {
    id: "risk-2",
    skillId: "risk",
    title: "Size a short at resistance",
    type: "build-order",
    scenario:
      "BTC rallied into 130 twice and got rejected both times. It just failed a third time and is turning back down. You want to go short. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 118, high: 122, low: 117, close: 121 },
      { open: 121, high: 126, low: 120, close: 124 },
      { open: 124, high: 130, low: 122, close: 125 },
      { open: 125, high: 128, low: 121, close: 122 },
      { open: 122, high: 130, low: 121, close: 123 },
      { open: 123, high: 126, low: 118, close: 119 },
    ],
    currentPrice: 119,
    entryDefault: 119,
    stopLossDefault: 134,
    takeProfitDefault: 88,
    entryRange: { min: 117, max: 121 },
    stopLossRange: { min: 132, max: 137 },
    takeProfitRange: { min: 82, max: 92 },
    sliderMin: 75,
    sliderMax: 140,
    sliderStep: 0.5,
    explain:
      "Entry near the current price (117-121) means you're shorting the confirmed rejection, not guessing the top would hold beforehand. The stop sits just above resistance (132-137), giving room for a false breakout without exposing you to a real trend reversal. A target of 82-92 keeps reward at roughly 2x or more of the risk (about $13-18 of risk vs. $27-35 of reward) — a short setup is graded on the same ratio as a long one, just flipped.",
  },
  {
    id: "risk-3",
    skillId: "risk",
    title: "Size a short at a double top",
    type: "build-order",
    scenario:
      "BTC has stalled out at 250 twice now, forming a double top, and just broke down from the second rejection. You want to go short. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 230, high: 245, low: 228, close: 240 },
      { open: 240, high: 250, low: 236, close: 238 },
      { open: 238, high: 244, low: 230, close: 233 },
      { open: 233, high: 248, low: 231, close: 236 },
      { open: 236, high: 250, low: 232, close: 234 },
      { open: 234, high: 240, low: 224, close: 227 },
    ],
    currentPrice: 227,
    entryDefault: 227,
    stopLossDefault: 255,
    takeProfitDefault: 173,
    entryRange: { min: 224, max: 229 },
    stopLossRange: { min: 252, max: 258 },
    takeProfitRange: { min: 165, max: 180 },
    sliderMin: 160,
    sliderMax: 260,
    sliderStep: 1,
    explain:
      "Entry near current price (224-229) confirms the breakdown from the double top rather than anticipating it. A stop above both rejection highs (252-258) survives a retest of the pattern without eating a full reversal back through it. A target of 165-180 banks at least 2x the risk you're taking (about $23-34 of risk vs. $47-64 of reward).",
  },
  {
    id: "risk-4",
    skillId: "risk",
    title: "The 1-2% rule",
    type: "signal-spot",
    candles: [
      { open: 100, high: 103, low: 99, close: 102 },
      { open: 102, high: 105, low: 101, close: 103 },
      { open: 103, high: 106, low: 102, close: 105 },
      { open: 105, high: 107, low: 103, close: 104 },
    ],
    prompt:
      "Your account has $10,000. Your risk-management plan caps risk at 2% of account equity per trade. What's the maximum you should be willing to lose if this trade hits your stop-loss?",
    options: ["$200", "$2,000", "$500"],
    correctIndex: 0,
    explain:
      "2% of $10,000 is $200. Capping risk per trade at 1-2% of equity means even a long losing streak — 10 losses in a row — only costs 20% of the account, not enough to wipe you out or force you into desperate, oversized trades trying to recover.",
  },
  {
    id: "risk-5",
    skillId: "risk",
    title: "Judging risk/reward",
    type: "signal-spot",
    candles: [
      { open: 52, high: 53, low: 49, close: 51 },
      { open: 51, high: 52, low: 48, close: 49 },
      { open: 49, high: 51, low: 47.5, close: 50 },
    ],
    prompt:
      "A trader buys at $50, sets a stop-loss at $47, and a take-profit at $53. Is this trade's risk/reward ratio good or bad?",
    options: [
      "Good — the reward is more than twice the risk",
      "Bad — risk and reward are equal (1:1), so the trade needs a high win rate just to break even",
      "It doesn't matter as long as the trade wins",
    ],
    correctIndex: 1,
    explain:
      "Risk is $3 (50 to 47) and reward is $3 (50 to 53) — a 1:1 ratio. With 1:1 risk/reward you need to win well over 50% of your trades just to break even after fees and slippage, let alone grow the account. Most disciplined traders look for at least 2:1 before taking a setup at all.",
  },
  {
    id: "risk-6",
    skillId: "risk",
    title: "Sizing a tight range setup",
    type: "build-order",
    scenario:
      "BTC has been chopping quietly between 48 and 52 for the last several candles — a tight, range-bound market. You want to buy near the bottom of the range. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 50, high: 51, low: 49, close: 50.5 },
      { open: 50.5, high: 52, low: 49.5, close: 50 },
      { open: 50, high: 51.5, low: 48.5, close: 49 },
      { open: 49, high: 50.5, low: 48, close: 49.5 },
      { open: 49.5, high: 51, low: 48, close: 48.5 },
      { open: 48.5, high: 50, low: 48, close: 49.5 },
    ],
    currentPrice: 49.5,
    entryDefault: 49.5,
    stopLossDefault: 47.3,
    takeProfitDefault: 53,
    entryRange: { min: 48.5, max: 50 },
    stopLossRange: { min: 47, max: 47.8 },
    takeProfitRange: { min: 52, max: 54 },
    sliderMin: 44,
    sliderMax: 56,
    sliderStep: 0.25,
    explain:
      "This is a quiet, range-bound market — the stop can be tight (47-47.8, just under the range floor at 48) because the price hasn't shown big violent swings while the range has held. That tight stop is exactly what makes a small move a solid reward: a target of 52-54, at the top of the range, still banks roughly 2x the ~$1.50-2 you're risking. Notice how much closer this stop sits to entry than the volatile breakout in the next lesson — stop distance should track the market's actual volatility, not a fixed dollar amount.",
  },
  {
    id: "risk-7",
    skillId: "risk",
    title: "Sizing a volatile breakout",
    type: "build-order",
    scenario:
      "BTC just broke out above resistance on a volatile move, gapping and whipsawing $20-30 a candle along the way. You want to buy the breakout. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 200, high: 210, low: 195, close: 205 },
      { open: 205, high: 225, low: 200, close: 220 },
      { open: 220, high: 240, low: 210, close: 215 },
      { open: 215, high: 245, low: 205, close: 238 },
      { open: 238, high: 260, low: 225, close: 250 },
      { open: 250, high: 270, low: 235, close: 262 },
    ],
    currentPrice: 262,
    entryDefault: 262,
    stopLossDefault: 232,
    takeProfitDefault: 322,
    entryRange: { min: 258, max: 266 },
    stopLossRange: { min: 228, max: 236 },
    takeProfitRange: { min: 315, max: 330 },
    sliderMin: 190,
    sliderMax: 340,
    sliderStep: 1,
    explain:
      "This market is swinging $20-30 candle to candle — a tight stop like the range-bound setup in the last lesson would get clipped by normal noise almost immediately. The stop here sits well below the breakout, around the old resistance-turned-support zone (228-236), giving the trade room to breathe. Because the stop is wider (~$26-38 of risk), the target has to scale with it too — 315-330 is roughly 2x that risk, not an arbitrary number. Same rule as the last lesson, opposite conclusion: match your stop distance to the market's actual volatility.",
  },
  {
    id: "risk-8",
    skillId: "risk",
    title: "Moving a stop under pressure",
    type: "signal-spot",
    candles: [
      { open: 40000, high: 40200, low: 39500, close: 39800 },
      { open: 39800, high: 39900, low: 39000, close: 39100 },
      { open: 39100, high: 39300, low: 38000, close: 38200 },
      { open: 38200, high: 38400, low: 37000, close: 37200 },
    ],
    prompt:
      "A trader buys BTC at $40,000 with a stop-loss at $39,000. Price falls to $39,050, and instead of letting the stop trigger, the trader moves the stop down to $37,000 to \"give the trade more room.\" Price keeps falling to $37,000 and the trader takes a much bigger loss than planned. What went wrong?",
    options: [
      "Nothing — moving a stop to avoid a loss is smart risk management",
      "The trader abandoned their pre-planned exit to avoid admitting the trade was wrong, turning a small planned loss into a much larger unplanned one",
      "The stop-loss should have been moved up, not down",
    ],
    correctIndex: 1,
    explain:
      "A stop-loss only protects you if it's honored. Moving it further away after the trade goes against you isn't \"giving it room\" — it's refusing to accept the original plan was wrong, and it turned a controlled $1,000 loss into an uncontrolled $3,000 one. The only good reasons to adjust a stop are to lock in profit as a trade moves in your favor, or because genuinely new information changes the setup — never just to avoid taking the loss you already planned for.",
  },
  {
    id: "risk-9",
    skillId: "risk",
    title: "Sizing a breakout entry",
    type: "build-order",
    scenario:
      "BTC has been resisted at 150 for weeks. It just closed above 150 for the first time, confirming a breakout. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 140, high: 148, low: 138, close: 145 },
      { open: 145, high: 150, low: 143, close: 147 },
      { open: 147, high: 150, low: 144, close: 146 },
      { open: 146, high: 151, low: 145, close: 150 },
      { open: 150, high: 156, low: 149, close: 154 },
    ],
    currentPrice: 154,
    entryDefault: 154,
    stopLossDefault: 147,
    takeProfitDefault: 169,
    entryRange: { min: 152, max: 156 },
    stopLossRange: { min: 145, max: 148 },
    takeProfitRange: { min: 166, max: 175 },
    sliderMin: 130,
    sliderMax: 180,
    sliderStep: 0.5,
    explain:
      "Entering at 152-156 confirms you're buying the breakout, not chasing it far above where it actually happened — the further above the breakout you pay, the worse your risk/reward gets even with the same stop. The stop belongs just under the old resistance (145-148), now acting as support; a break back below it invalidates the breakout thesis. A target of 166-175 banks roughly 2x the ~$6-9 you're risking.",
  },
  {
    id: "risk-10",
    skillId: "risk",
    title: "Sizing a pullback entry",
    type: "build-order",
    scenario:
      "BTC is in a clear uptrend and just pulled back to a prior support zone around 87-90 before turning back up. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 75, high: 80, low: 74, close: 78 },
      { open: 78, high: 88, low: 77, close: 86 },
      { open: 86, high: 95, low: 85, close: 92 },
      { open: 92, high: 94, low: 89, close: 90 },
      { open: 90, high: 91, low: 87, close: 88 },
      { open: 88, high: 93, low: 87, close: 92 },
    ],
    currentPrice: 92,
    entryDefault: 92,
    stopLossDefault: 85,
    takeProfitDefault: 107,
    entryRange: { min: 90, max: 94 },
    stopLossRange: { min: 83, max: 86 },
    takeProfitRange: { min: 104, max: 112 },
    sliderMin: 70,
    sliderMax: 118,
    sliderStep: 0.5,
    explain:
      "Buying the pullback (90-94) instead of chasing the earlier rally gets a tighter, more logical stop than buying at the top of the prior leg would have. The stop sits just under the pullback low (83-86) — a break below that says the uptrend has actually failed, not just paused. A target of 104-112 is roughly 2x the ~$6-9 of risk, in line with the size of the trend's prior swing.",
  },
  {
    id: "risk-11",
    skillId: "risk",
    title: "Position sizing math",
    type: "signal-spot",
    candles: [
      { open: 20, high: 22, low: 19, close: 21 },
      { open: 21, high: 23, low: 20, close: 22.5 },
      { open: 22.5, high: 24, low: 21, close: 23 },
    ],
    prompt:
      "Account size: $5,000. Max risk per trade: 1% ($50). Your stop-loss is $2 away from your entry. How many units should you buy so a stopped-out trade loses exactly $50?",
    options: ["25 units", "50 units", "100 units", "2.5 units"],
    correctIndex: 0,
    explain:
      "Position size = (account x risk%) / stop distance = ($5,000 x 1%) / $2 = $50 / $2 = 25 units. If the stop hits, you lose exactly $50 — 1% of the account — no matter what the asset's price is. This formula is the mechanical version of \"size the position to fit the risk,\" not the other way around: the stop distance and risk budget decide the size, not a gut-feel dollar amount.",
  },
  {
    id: "risk-12",
    skillId: "risk",
    title: "Why all-in sizing fails",
    type: "signal-spot",
    candles: [
      { open: 100, high: 104, low: 98, close: 103 },
      { open: 103, high: 108, low: 101, close: 107 },
      { open: 107, high: 110, low: 104, close: 106 },
    ],
    prompt:
      "A trader has a setup they're extremely confident in, so they put 100% of their account into it instead of their usual 1-2% risk. The setup works and price moves in their favor. Why is this still a dangerous habit, even though it worked this time?",
    options: [
      "It isn't dangerous — if the setup is right, sizing doesn't matter",
      "One correct trade doesn't change the math: a single unexpected move — a wick through the stop, an outage, a flash crash — can wipe out the account, and getting away with it once makes doing it again more likely",
      "It's only dangerous if you're using leverage",
    ],
    correctIndex: 1,
    explain:
      "No setup is 100% certain — even a great trade can be stopped out by ordinary volatility, and an all-in position turns any single bad moment into an account-ending one. Winning once on an oversized bet doesn't validate the habit; it just delays the trade that ends it. Consistent 1-2% risk sizing exists precisely so that no single trade, right or wrong, can end the account.",
  },
  {
    id: "risk-13",
    skillId: "risk",
    title: "Sizing a mean-reversion bounce",
    type: "build-order",
    scenario:
      "BTC dropped sharply and is now showing early signs of a bounce off a well-tested support level around 300. You want to buy the reversion. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 340, high: 345, low: 330, close: 333 },
      { open: 333, high: 336, low: 315, close: 318 },
      { open: 318, high: 322, low: 300, close: 305 },
      { open: 305, high: 310, low: 298, close: 302 },
      { open: 302, high: 315, low: 300, close: 312 },
    ],
    currentPrice: 312,
    entryDefault: 312,
    stopLossDefault: 295,
    takeProfitDefault: 344,
    entryRange: { min: 308, max: 314 },
    stopLossRange: { min: 292, max: 297 },
    takeProfitRange: { min: 338, max: 352 },
    sliderMin: 280,
    sliderMax: 360,
    sliderStep: 1,
    explain:
      "Mean-reversion trades need the entry near confirmation of the bounce (308-314), not at the exact bottom — nobody reliably picks the exact low. The stop belongs just under the support zone (292-297); if it breaks, the \"bounce\" thesis is wrong and this is a continuing downtrend, not a reversion. A target of 338-352 is roughly 2x the ~$14-19 of risk — reasonable, since mean-reversion bounces often only retrace part of the prior drop, not reach the old highs.",
  },
  {
    id: "risk-14",
    skillId: "risk",
    title: "Sizing a trend continuation",
    type: "build-order",
    scenario:
      "BTC is in a strong uptrend and just consolidated sideways for a few candles before pushing higher again — a continuation, not a reversal. Set your entry, stop-loss, and take-profit.",
    candles: [
      { open: 400, high: 415, low: 395, close: 410 },
      { open: 410, high: 425, low: 405, close: 420 },
      { open: 420, high: 424, low: 412, close: 416 },
      { open: 416, high: 420, low: 410, close: 414 },
      { open: 414, high: 418, low: 409, close: 413 },
      { open: 413, high: 430, low: 411, close: 427 },
    ],
    currentPrice: 427,
    entryDefault: 427,
    stopLossDefault: 406,
    takeProfitDefault: 467,
    entryRange: { min: 423, max: 429 },
    stopLossRange: { min: 403, max: 408 },
    takeProfitRange: { min: 460, max: 476 },
    sliderMin: 380,
    sliderMax: 490,
    sliderStep: 1,
    explain:
      "Entering as price breaks back above the consolidation (423-429) confirms the trend is resuming, rather than guessing when it will. The stop belongs under the consolidation's low (403-408) — a move back below it means the \"pause\" was actually a reversal. A target of 460-476 banks roughly 2x the ~$18-23 of risk, in line with the size of the prior leg up.",
  },
];
